language: python
python:
  - 2.7_with_system_site_packages
  - '3.5.1'
  - pypy
cache:
  directories:
    - $HOME/.cache/pip

sudo: false
matrix:
  fast_finish: true

install: make setup
script: make test
